"""
LicenseSeal auto-remediation bot
================================
Audits a tree, injects/updates missing markers, and optionally prepares a GitHub
Pull Request. External services are optional; local autofix/dry-run is always
available.
"""
from __future__ import annotations

import os
import subprocess
from dataclasses import dataclass, field
from pathlib import Path

from .core import (
    DEFAULT_EXCLUDE_DIRS,
    InjectionConfig,
    audit_project,
    inject_project,
)


@dataclass
class AutoFixResult:
    root: str
    before_total: int
    before_marked: int
    before_missing: int
    changed: int
    errors: int
    branch: str = ""
    commit_created: bool = False
    pr_url: str = ""
    messages: list[str] = field(default_factory=list)

    def to_dict(self) -> dict:
        return self.__dict__.copy()


def _run(cmd: list[str], cwd: Path, check: bool = True) -> subprocess.CompletedProcess:
    return subprocess.run(cmd, cwd=cwd, text=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, check=check)


def git_available(root: Path) -> bool:
    try:
        _run(["git", "rev-parse", "--is-inside-work-tree"], root)
        return True
    except Exception:
        return False


def ensure_branch(root: Path, branch: str) -> str:
    _run(["git", "checkout", "-B", branch], root)
    return branch


def commit_changes(root: Path, message: str) -> bool:
    if not git_available(root):
        return False
    status = _run(["git", "status", "--porcelain"], root, check=False).stdout.strip()
    if not status:
        return False
    _run(["git", "add", "."], root)
    _run(["git", "commit", "-m", message], root)
    return True


def create_github_pr(root: Path, branch: str, title: str, body: str, base: str = "") -> str:
    """Create a PR using GitHub CLI when available; returns URL or empty string."""
    gh = os.environ.get("GITHUB_TOKEN") or os.environ.get("GH_TOKEN")
    if not gh:
        return ""
    try:
        _run(["git", "push", "-u", "origin", branch], root)
        cmd = ["gh", "pr", "create", "--title", title, "--body", body, "--head", branch]
        if base:
            cmd.extend(["--base", base])
        res = _run(cmd, root, check=False)
        if res.returncode == 0:
            return res.stdout.strip().splitlines()[-1]
    except Exception:
        return ""
    return ""


def autofix_project(
    root: Path,
    *,
    license_id: str = "MIT",
    owner: str = "UNKNOWN",
    project: str = "",
    include_configs: bool = False,
    update: bool = True,
    dry_run: bool = False,
    create_pr: bool = False,
    branch: str = "",
    base_branch: str = "",
    exclude_dirs: set[str] | None = None,
) -> AutoFixResult:
    root = root.resolve()
    total, marked, unmarked, verification = audit_project(root, include_configs, exclude_dirs)
    cfg = InjectionConfig(
        root=root,
        license_id=license_id,
        owner=owner,
        project=project or root.name,
        include_configs=include_configs,
        update=update,
        dry_run=dry_run,
        write_policy=False,
        exclude_dirs=set(DEFAULT_EXCLUDE_DIRS) | set(exclude_dirs or set()),
    )
    branch_name = branch or f"licenseseal/auto-fix-{os.environ.get('GITHUB_RUN_ID', 'local')}"
    messages: list[str] = []
    if create_pr and not dry_run and git_available(root):
        ensure_branch(root, branch_name)
        messages.append(f"checked out branch {branch_name}")

    results = inject_project(cfg)
    changed = sum(1 for r in results if r.action in {"injected", "updated", "would_inject", "would_update"})
    errors = sum(1 for r in results if r.action == "error")
    committed = False
    pr_url = ""

    if changed and create_pr and not dry_run and git_available(root):
        committed = commit_changes(root, "chore: apply LicenseSeal auto-remediation")
        if committed:
            pr_url = create_github_pr(
                root,
                branch_name,
                "Apply LicenseSeal auto-remediation",
                "This pull request was generated by LicenseSeal to inject or refresh provenance markers.",
                base_branch or os.environ.get("GITHUB_BASE_REF", ""),
            )
            if pr_url:
                messages.append(f"created PR {pr_url}")
            else:
                messages.append("changes committed; PR creation skipped or failed")

    return AutoFixResult(
        root=str(root),
        before_total=total,
        before_marked=marked,
        before_missing=len(unmarked),
        changed=changed,
        errors=errors,
        branch=branch_name if create_pr else "",
        commit_created=committed,
        pr_url=pr_url,
        messages=messages,
    )
